### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by lapo-luchini** [v12/angular-xslt#1]
Hi! Reading the code, it seems that IE5+ is supported… but in IE11 it always goes `Not supported by your browser` to me.

Is that supposed to work? Or is that IE5-related comment something from an old version? (the example page doesn't even load on IE8-, as expected on Angular 1.3)

**Comment by lapo-luchini** [comment]
I committed a change what works well enough for my use-case in andxor/angular-xslt@3e72195bdb962fbf0b181b2bdc377921bf8ab2a1, feel free to take a look and/or import code.

**Comment by v12** [comment]
@lapo-luchini ah, cool, thanks. You've got it done quicker than me. :+1: I'm working on it right now and did it exactly the same way. Either way thank you.

You can file a pull request if you want :wink: 

Also, later on today I'll push changes that include test coverage for the code, so it'll be easy to make sure that any further changes won't break it anymore and it works as expected.
