### ISSUE TITLE
How to convert in XML & XSLT data in angular6

### ISSUE THREAD

**Issue by JaiKumaresh** [v12/angular-xslt#3]
I have XML & XSLT response. And I needed that how to merge that in [Here](http://krtnio.github.io/angular-xslt/)
If anyone knows that plz tell

**Comment by v12** [comment]
Unfortunately, this is AngularJS v1.x version and there is no plan to create Angular 2+ module.

PRs are welcome though. 👍

**Comment by anjiJaUz** [comment]
Hello  Jai Kumaresh,

Try using this:
https://github.com/patrikx3/angular-compile
Works very nice!

Best!

AnjiJa

**Comment by anjiJaUz** [comment]
Hello  Jai Kumaresh,

Try using this:
https://github.com/patrikx3/angular-compile
Works very nice!

Best!

AnjiJa
